#!/bin/bash
title=virt
description="- Installs and configures qemu and libvirt"
status=off

main() {
    commandFailure="Installing qemu and libvirt has failed." &&
        install qemu libvirt virtiofsd polkit dbus netcat

    commandFailure="Modifying qemu and libvirt configs has failed."
    sed -i -e 's/#unix_sock_group = "libvirt"/unix_sock_group = "libvirt"/g' /mnt/etc/libvirt/libvirtd.conf || die
    sed -i -e 's/#unix_sock_rw_perms = "0770"/unix_sock_rw_perms = "0770"/g' /mnt/etc/libvirt/libvirtd.conf || die

    if [ -n "$username" ]; then
        sed -i -e 's/#user = "libvirt"/user = "'$username'"/g' /mnt/etc/libvirt/qemu.conf || die
        sed -i -e 's/#group = "libvirt"/group = "'$username'"/g' /mnt/etc/libvirt/qemu.conf || die

        commandFailure="Adding user to libvirt group has failed." &&
            system "usermod -aG libvirt $username"
    fi

    chroot /mnt /bin/bash -c "ln -s /etc/sv/libvirtd /var/service" 2>/dev/null || echo "Warning: libvirtd service already enabled, skipping."
    chroot /mnt /bin/bash -c "ln -s /etc/sv/virtlogd /var/service" 2>/dev/null || echo "Warning: virtlogd service already enabled, skipping."
    chroot /mnt /bin/bash -c "ln -s /etc/sv/virtlockd /var/service" 2>/dev/null || echo "Warning: virtlockd service already enabled, skipping."

    # dbus and polkitd may or may not be installed by other things, recheck
    [ ! -e /mnt/etc/runit/runsvdir/default/dbus ] &&
        { chroot /mnt /bin/bash -c "ln -s /etc/sv/dbus /var/service" 2>/dev/null || echo "Warning: dbus service already enabled, skipping." ; }

    grep "gid=proc /proc" /mnt/etc/rc.local && ! chroot /mnt /bin/bash -c "groups polkitd | grep proc" &&
        { commandFailure="Adding polkitd user to proc group has failed." ; system "usermod -aG proc polkitd" ; }

    return 0
}